### ISSUE TITLE
this.ready.tap is not a function when using example.js

### ISSUE THREAD

**Issue by Latiosu** [llambda/brute-knex#11]
# Description
Unable to see working example when running example.js.

# Steps to Reproduce
1. Checkout eddcda4
2. Install dependencies with `yarn`
3. Run with `node example`
4. Visit http://localhost:3000

## Expected Outcome
See "Success" message

## Actual Outcome
See stack trace with message: "TypeError: this.ready.tap is not a function"

## Screenshot
![image](https://user-images.githubusercontent.com/7020503/79674399-2dfaca00-8226-11ea-95de-c53f776ed6a2.png)

**Comment by Latiosu** [comment]
Noticed that this issue doesn't occur in previous commit (ae3d8158cc3a1ca47dc69a15cfac47ed66ae0862).

**Comment by NGPixel** [comment]
I refactored brute-knex to work without bluebird (which has been removed in Knex 0.20+) and switched most of the code to use async / await:
https://github.com/Requarks/wiki/blob/master/server/helpers/brute-knex.js
